---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fernandapereira-frontend-recommend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fernandapereira-frontend
  template:
    metadata:
      labels:
        app: fernandapereira-frontend
    spec:
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: project2-pvc-fernandapereira
      containers:
        - name: fernandapereira-frontend
        imagePullPolicy: Always
        image: fernandapereira/frontend:0.1
        volumeMounts:
          - mountPath: "/shared"
          name: shared
        ports:
          - containerPort: 32180
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fernandapereira-generator-recommend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fernandapereira-generator
  template:
    metadata:
      labels:
        app: fernandapereira-generator
  spec:
    volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: project2-pvc-fernandapereira
    containers:
    - name: fernandapereira-generator
      imagePullPolicy: Always
      image: fernandapereira/generator:0.1
      volumeMounts:
        - mountPath: "/shared"
        name: shared
      ports:
      - containerPort: 32180
---